-- AlterTable
ALTER TABLE "User" ADD COLUMN     "age" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "creditScore" INTEGER NOT NULL DEFAULT 850,
ADD COLUMN     "employer" TEXT NOT NULL DEFAULT 'none';
